// <auto-generated />
using System;
using Maliev.NotificationService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Maliev.NotificationService.Data.Migrations
{
    [DbContext(typeof(NotificationDbContext))]
    [Migration("20251217022507_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Maliev.NotificationService.Data.Entities.ChannelBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChannelIdentifier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel_identifier");

                    b.Property<string>("ChannelType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("channel_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("InvalidatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invalidated_at");

                    b.Property<string>("InvalidatedReason")
                        .HasColumnType("text")
                        .HasColumnName("invalidated_reason");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_valid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_channel_bindings");

                    b.HasIndex("IsValid")
                        .HasDatabaseName("ix_channel_bindings_is_valid");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_channel_bindings_user_id");

                    b.HasIndex("UserId", "ChannelType")
                        .IsUnique()
                        .HasDatabaseName("ix_channel_bindings_user_id_channel_type");

                    b.ToTable("channel_bindings");
                });

            modelBuilder.Entity("Maliev.NotificationService.Data.Entities.DeadLetterRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("EscalatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("escalated_at");

                    b.Property<string>("EscalationStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("escalation_status");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_id");

                    b.Property<string>("EventPayload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_payload");

                    b.Property<string>("FailureReasons")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("failure_reasons");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("resolved_by");

                    b.Property<int>("TotalAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("total_attempts");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_dead_letter_records");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_dead_letter_records_created_at");

                    b.HasIndex("EscalationStatus")
                        .HasDatabaseName("ix_dead_letter_records_escalation_status");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_dead_letter_records_event_id");

                    b.ToTable("dead_letter_records");
                });

            modelBuilder.Entity("Maliev.NotificationService.Data.Entities.DeliveryLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_number");

                    b.Property<string>("ChannelType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("channel_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_id");

                    b.Property<string>("MessageContent")
                        .HasColumnType("text")
                        .HasColumnName("message_content");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_message_id");

                    b.Property<string>("ProviderResponse")
                        .HasColumnType("text")
                        .HasColumnName("provider_response");

                    b.Property<string>("RecipientIdentifier")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("recipient_identifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_delivery_logs");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_delivery_logs_created_at");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_delivery_logs_event_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_delivery_logs_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_delivery_logs_user_id");

                    b.ToTable("delivery_logs");
                });

            modelBuilder.Entity("Maliev.NotificationService.Data.Entities.NotificationTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChannelType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("channel_type");

                    b.Property<string>("ContentTemplate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_template");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language");

                    b.PrimitiveCollection<string>("Parameters")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("parameters");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("template_key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_notification_templates");

                    b.HasIndex("TemplateKey")
                        .HasDatabaseName("ix_notification_templates_template_key");

                    b.HasIndex("TemplateKey", "Version", "Language", "ChannelType")
                        .IsUnique()
                        .HasDatabaseName("ix_notification_templates_template_key_version_language_channe~");

                    b.ToTable("notification_templates");
                });

            modelBuilder.Entity("Maliev.NotificationService.Data.Entities.RetryQueueEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_number");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_id");

                    b.Property<string>("EventPayload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_payload");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("ScheduledTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_time");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_retry_queue_entries");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_retry_queue_entries_event_id");

                    b.HasIndex("ScheduledTime")
                        .HasDatabaseName("ix_retry_queue_entries_scheduled_time");

                    b.ToTable("retry_queue_entries");
                });

            modelBuilder.Entity("Maliev.NotificationService.Data.Entities.UserNotificationPreference", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FallbackChannelTypes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("fallback_channel_types");

                    b.Property<string>("OptOutCategories")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("opt_out_categories");

                    b.Property<string>("PrimaryChannelType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("primary_channel_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId")
                        .HasName("pk_user_notification_preferences");

                    b.HasIndex("PrimaryChannelType")
                        .HasDatabaseName("ix_user_notification_preferences_primary_channel_type");

                    b.ToTable("user_notification_preferences");
                });
#pragma warning restore 612, 618
        }
    }
}
