<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <SharedLibraryVersion Condition="'$(SharedLibraryVersion)' == ''">1.0.*-*</SharedLibraryVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Maliev.NotificationService.Domain\Maliev.NotificationService.Domain.csproj" />
  </ItemGroup>

</Project>
